waypoints:
  - name: nn
    frame_id: map
    pose:
      position:
        x: 3.82357
        y: -1.05742
        z: 0
      orientation:
        x: 0
        y: 0
        z: 0
        w: 1
  - name: aa
    frame_id: map
    pose:
      position:
        x: 1.35944
        y: -0.0110075
        z: 0
      orientation:
        x: 0
        y: 0
        z: 0
        w: 1
