# ConstructYaml.msg

# List of names for the poses
string[] pose_names

# Corresponding list of PoseStamped messages
geometry_msgs/PoseStamped[] poses
geometry_msgs/Pose[] scene_poses
bool loop
---
bool status      # 1 [ok] | -1 [not ok]