string request_string # which_map_do_you_have | save_map | select_map | mapping | navi | remapping
string map_name_to_save
string map_name_to_select
---
int16 total_maps
string[] map_names
int16 status      

# -1 [service not ok], 1 [service ok], 
# 2 [maps exist], 3 [maps do not exist], 
# 4 [save map ok], 5 [save map not ok]
# 6 [select map ok], 7 [select map not ok], 

# 8 [mapping mode ok], 9 [mapping mode not ok],
# 10 [navi mode ok], 11 [navi mode not ok]
# 12 [remapping mode ok], 13 [remapping mode not ok]